import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,mkdir} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';
const dir=await mkdtemp(path.join(os.tmpdir(),'spa-test-'));await mkdir('test-results',{recursive:true});
const records=[{id:'1',itemId:'1',sourceBoardId:'18391791372',sourceBoard:'D2D',source:'D2D',name:'Alpha',owner:'Owner A',assignedResource:'Crew A',type:'MDU',status:'Ready',city:'Lander, WY',sourceUrl:'https://example.test/1'},{id:'2',itemId:'2',sourceBoardId:'5077578194',sourceBoard:'Project Tracker',source:'Project Tracker',name:'Alpha tracker',owner:'Owner A',assignedResource:'Crew A',status:'Conditional',city:'Cheyenne, WY',sourceUrl:'https://example.test/2'},{id:'3',itemId:'3',sourceBoardId:'18391791372',sourceBoard:'D2D',source:'D2D',name:'Gamma',owner:'Owner B',assignedResource:'Unassigned',status:'Blocked',city:'Sheridan, WY',sourceUrl:'https://example.test/3'}];
await writeFile(path.join(dir,'seed.json'),JSON.stringify({records}));await writeFile(path.join(dir,'project-bridge.json'),JSON.stringify({links:[{d2dItemId:'1',trackerItemId:'2'}]}));await writeFile(path.join(dir,'monday-users.json'),JSON.stringify({users:[{id:'100',name:'Crew A',enabled:true}]}));
const port=18820;const server=spawn(process.execPath,['server.mjs'],{env:{...process.env,PORT:String(port),SPA_DATA_DIR:dir,MONDAY_API_KEY:''},stdio:['ignore','pipe','pipe']});let serverLog='';server.stdout.on('data',d=>serverLog+=d);server.stderr.on('data',d=>serverLog+=d);let browser;const results=[];
try{
for(let n=0;n<50;n++){try{await fetch(`http://127.0.0.1:${port}/api/health`);break;}catch{await new Promise(r=>setTimeout(r,100));}}
browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});const context=await browser.newContext({baseURL:`http://127.0.0.1:${port}`,viewport:{width:1700,height:1100},permissions:['clipboard-read','clipboard-write']});const page=await context.newPage(),errors=[];page.setDefaultTimeout(6000);page.on('pageerror',e=>errors.push(e.message));
async function check(name,fn){try{await fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.log('FAIL',name,e.message);await page.screenshot({path:'test-results/failure-'+results.length+'.png',fullPage:true});}}
await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'networkidle'});
await check('build label and connected truth',async()=>{await page.locator('#health').filter({hasText:'R20-workflow'}).waitFor();assert((await page.locator('#health').innerText()).includes('connected: false'));});
await check('all generalized workflow bubbles act',async()=>{for(const label of ['All open','Ready','Conditional','Blocked','Unassigned resource','Needs update','Readiness blockers','Source bridge gaps','Schedule candidates','Tuesday update prep']){await page.locator('#chips').getByRole('button',{name:label,exact:true}).click();if(label==='Tuesday update prep')await page.locator('#tuesdayRows').filter({hasText:'automatic sending disabled'}).waitFor();else assert((await page.locator('#workflowStatus').innerText()).startsWith(label+':'));}});
await check('single-click project source IDs and gates',async()=>{await page.getByRole('button',{name:'Work',exact:true}).click();await page.locator('#chips').getByRole('button',{name:'All open',exact:true}).click();await page.locator('#list .card').filter({hasText:'Alpha tracker'}).click();await page.locator('#inspector[data-loading="false"] code').filter({hasText:'5077578194'}).first().waitFor();assert((await page.locator('#inspector').innerText()).includes('Bridge: verified'));assert((await page.locator('#inspector').innerText()).includes('Not qualified for dispatch'));});
await check('extract realistic note then edit draft controls',async()=>{await page.locator('#pcNotes').fill('Owner is Owner A; assign Kyle Davis; RFS date to 11-25; install date 11/30/2026; blocker is Housing approval; action is Confirm resource; priority hot; status ready.');await page.getByRole('button',{name:'Extract into fields',exact:true}).click();await page.waitForFunction(()=>document.getElementById('pcPreview').textContent.includes('Extracted'));assert.equal(await page.locator('#pcRfs').inputValue(),'2026-11-25');await page.locator('#pcBlocker').fill('Permit followup');await page.getByRole('button',{name:'Add update to draft',exact:true}).click();assert((await page.locator('#draft').inputValue()).includes('Permit followup'));assert((await page.locator('#writeState').innerText()).includes('Draft created'));});
await check('verified dual dry run and queue do not post',async()=>{await page.locator('#dest').selectOption('both');await page.getByRole('button',{name:'Dry run',exact:true}).click();await page.locator('#writeState').filter({hasText:'Dry run passed'}).waitFor();assert((await page.locator('#writeTest').innerText()).includes('18391791372'));assert((await page.locator('#writeTest').innerText()).includes('5077578194'));await page.locator('#inspector').getByRole('button',{name:'Queue',exact:true}).click();await page.locator('#writeState').filter({hasText:'Queued'}).waitFor();});
await check('unverified bridge blocks dual post in backend and UI',async()=>{await page.locator('#list .card').filter({hasText:'Gamma'}).click();await page.locator('#inspector[data-loading="false"] h2').filter({hasText:'Gamma'}).waitFor();await page.locator('#draft').fill('Test draft');await page.locator('#dest').selectOption('both');await page.getByRole('button',{name:'Dry run',exact:true}).click();await page.locator('#writeState').filter({hasText:'Verified bridge required'}).waitFor();const r=await page.request.post('/api/monday/dual-comment',{data:{itemId:'3',text:'Test',destinations:'both',confirmed:true}});assert.equal(r.status(),409);});
await check('people cache IDs and honest mention label',async()=>{await page.getByRole('button',{name:'Refresh people',exact:true}).click();await page.locator('#peoplePicker').selectOption('100');await page.getByRole('button',{name:'Insert text tag',exact:true}).click();assert((await page.locator('#peopleStatus').innerText()).includes('not a verified native mention'));});
await check('actual double-click meeting runner preserves single editor',async()=>{await page.locator('#list .card').filter({hasText:'Gamma'}).dblclick();await page.locator('#modal.open').waitFor();assert.equal(await page.locator('#pcNotes').count(),1);await page.keyboard.press('Escape');});
await check('Tuesday preview queue copy export and dedup',async()=>{await page.getByRole('button',{name:'Tuesday RFS Prep',exact:true}).click();await page.locator('.tuesdayPick').first().waitFor();await page.locator('.tuesdayPick').first().check();await page.locator('#tuesdayMessage0').fill('Please provide a checkpoint update.');await page.getByRole('button',{name:'Queue selected',exact:true}).click();await page.locator('#tuesdayActionStatus').filter({hasText:'Queued'}).waitFor();await page.getByRole('button',{name:'Queue selected',exact:true}).click();await page.locator('#tuesdayActionStatus').filter({hasText:'Duplicate blocked'}).waitFor();await page.getByRole('button',{name:'Copy selected',exact:true}).click();await page.waitForFunction(()=>document.getElementById('tuesdayExport').value.includes('Please provide'));const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Export request list',exact:true}).click();await dl;const cfg=await (await page.request.get('/api/reminders/config')).json();assert.equal(cfg.config.enabled,false);const rem=await (await page.request.post('/api/reminders/tuesday/run',{data:{force:true,dryRun:false}})).json();assert.equal(rem.posted,0);});
await check('three-job schedule selected IDs reorder sequence Teams export',async()=>{await page.evaluate(()=>showTab('route'));await page.locator('#schedDate').fill('2026-11-25');for(const id of ['1','2','3']){await page.locator('#schedProject').selectOption(id);await page.getByRole('button',{name:'Add to schedule',exact:true}).click();}assert.equal(await page.locator('#scheduleBoard').getByRole('button',{name:'Remove',exact:true}).count(),3);await page.locator('#scheduleBoard').getByRole('button',{name:'↓',exact:true}).first().click();await page.getByRole('button',{name:'Optimize routes',exact:true}).click();const text=await page.locator('#scheduleBoardExport').inputValue();for(const name of ['Alpha','Alpha tracker','Gamma','Let Kyle know'])assert(text.includes(name));await page.getByRole('button',{name:'Copy Teams schedule',exact:true}).click();assert(await page.locator('#scheduleBoard a').count()>0);});
await check('no browser JS errors',()=>assert.deepEqual(errors,[]));await page.screenshot({path:'test-results/schedule.png',fullPage:true});
await page.getByRole('button',{name:'Work',exact:true}).click();await page.locator('#chips').getByRole('button',{name:'All open',exact:true}).click();await page.locator('#list .card').filter({hasText:'Gamma'}).click();await page.waitForTimeout(200);await page.screenshot({path:'test-results/editor.png',fullPage:true});
}finally{await browser?.close();server.kill();await writeFile('test-results/browser-results.json',JSON.stringify({scope:'local served UI with isolated synthetic projects; not hosted/live-write acceptance',results},null,2));await writeFile('test-results/server.log',serverLog);}
if(results.some(r=>!r.pass))process.exitCode=1;
