import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile,mkdir} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {createWorkflow} from '../lib/workflow-server.mjs';
async function harness({failItem=null,readbackFail=false}={}){
const dir=await mkdtemp(path.join(os.tmpdir(),'spa-delivery-'));const files=Object.fromEntries(['queue','audit','bridge','tuesday','live','users'].map(k=>[k,path.join(dir,k+'.json')]));await writeFile(files.bridge,JSON.stringify({links:[{d2dItemId:'1',trackerItemId:'2'}]}));let calls=0;const updates=new Map();
const items=[{itemId:'1',sourceBoardId:'18391791372',name:'A',observationSource:'Monday sync',observedAt:'2026-10-05T00:00:00Z',owner:'PM',source:'D2D'},{itemId:'2',sourceBoardId:'5077578194',name:'A tracker',observationSource:'Monday sync',observedAt:'2026-10-05T00:00:00Z',owner:'PM',source:'Project Tracker'}];
const handler=createWorkflow({ROOT:process.cwd(),files,allItems:async()=>items,readJson:async(p,f)=>{try{return JSON.parse(await readFile(p,'utf8'));}catch{return f;}},mondayToken:async()=>'',parseBody:async r=>r.body,send:(res,status,obj)=>Object.assign(res,{status,obj}),mondayGraphql:async(q,v)=>{
 if(q.includes('items(ids:'))return {items:items.filter(x=>v.ids.includes(x.itemId)).map(x=>({id:x.itemId,board:{id:x.sourceBoardId}}))};
 if(q.includes('mutation')){calls++;if(v.item===failItem)throw Error('Controlled network failure');const id=String(calls+100);updates.set(id,{id,text_body:v.body,item:{id:v.item,board:{id:items.find(i=>i.itemId===v.item).sourceBoardId}}});return {create_update:{id}};}
 if(readbackFail)throw Error('Readback unavailable');return {updates:v.ids.map(id=>updates.get(id))};
}});
return {calls:()=>calls,request:async(p,body,m='POST')=>{const res={};try{await handler({method:m,body},res,new URL(p,'http://local'));return res.obj;}catch(e){return {error:e.message,status:e.status};}},files};
}
test('dual-post simulated readback and retry never duplicates',async()=>{const h=await harness();const b={itemId:'1',text:'Hello',destinations:'both',confirmed:true};const out=await h.request('/api/monday/dual-comment',b);assert.equal(out.readbackConfirmed,true);assert.equal(h.calls(),2);await h.request('/api/monday/dual-comment',b);assert.equal(h.calls(),2);});
test('partial mutation failure remains partial and no blind repost',async()=>{const h=await harness({failItem:'2'}),b={itemId:'1',text:'Hello',destinations:'both',confirmed:true};const out=await h.request('/api/monday/dual-comment',b);assert.equal(out.status,'Partial failure');await h.request('/api/monday/dual-comment',b);assert.equal(h.calls(),2);});
test('failed readback is not delivery success and retry reads existing ID',async()=>{const h=await harness({readbackFail:true}),b={itemId:'1',text:'Hello',destinations:'primary',confirmed:true};assert.equal((await h.request('/api/monday/dual-comment',b)).readbackConfirmed,false);await h.request('/api/monday/dual-comment',b);assert.equal(h.calls(),1);});
test('Tuesday preview no sends; selected queue/export and duplicate send suppression',async()=>{const h=await harness();const p=await h.request('/api/tuesday/prepare',null,'GET');assert.equal(h.calls(),0);const req={id:p.groups[0].items[0].id,text:'Checkpoint please'};await h.request('/api/tuesday/action',{action:'export',requests:[req]});const q=await h.request('/api/tuesday/action',{action:'queue',requests:[req]});assert.equal(q.results[0].status,'Queued');assert.equal(h.calls(),0);const first=await h.request('/api/tuesday/action',{action:'send',requests:[req],confirmed:true});assert.equal(first.results[0].readbackConfirmed,true);const again=await h.request('/api/tuesday/action',{action:'send',requests:[req],confirmed:true});assert.equal(again.results[0].status,'Duplicate blocked');assert.equal(h.calls(),1);});
test('unattended Tuesday request cannot send; native mention claim is blocked',async()=>{const h=await harness();const r=await h.request('/api/reminders/tuesday/run',{force:true,dryRun:false});assert.equal(r.posted,0);assert.equal(h.calls(),0);const out=await h.request('/api/monday/dual-comment',{itemId:'1',text:'test',mentionIds:['100'],confirmed:true});assert.equal(out.status,409);assert.equal(h.calls(),0);});
test('Tuesday external mark blocks later queued post; no auto mutation',async()=>{const h=await harness(),p=await h.request('/api/tuesday/prepare',null,'GET'),req={id:p.groups[0].items[0].id};await h.request('/api/tuesday/action',{action:'queue',requests:[req]});await h.request('/api/tuesday/action',{action:'mark-sent',requests:[req],confirmed:true});const out=await h.request('/api/queue/'+req.id+'/push',{confirmed:true});assert.equal(out.status,'Duplicate blocked');assert.equal(h.calls(),0);});
test('legacy inbound mirror cannot echo a manual dual post',async()=>{const h=await harness();const challenge=await h.request('/api/webhooks/monday/receive',{challenge:'test-challenge'});assert.equal(challenge.challenge,'test-challenge');const out=await h.request('/api/webhooks/monday/receive',{event:{type:'create_update',pulseId:'1',body:'hello'}});assert.equal(out.mirrorPosted,false);assert.equal(h.calls(),0);});
test('audit custody contains recipient, message, exact targets, timestamp, state and idempotency key',async()=>{
 const h=await harness(),b={itemId:'1',text:'EXACT mock sacrificial comment',destinations:'primary',confirmed:true};
 await h.request('/api/queue',b);const first=await h.request('/api/monday/comment',b),retry=await h.request('/api/monday/comment',b);
 assert.equal(h.calls(),1);assert.equal(first.posted[0].updateId,retry.posted[0].updateId);
 const rb=first.posted[0].readback;assert.equal(rb.itemId,'1');assert.equal(rb.boardId,'18391791372');assert.equal(rb.content,b.text);
 const rows=JSON.parse(await readFile(h.files.audit,'utf8'));for(const row of rows){assert(row.timestamp);assert(row.idempotencyKey);assert.equal(row.recipient,'PM');assert.equal(row.message,b.text);assert.equal(row.targets[0].itemId,'1');assert(row.status);}
 const storage=await h.request('/api/storage/status',null,'GET');assert.equal(storage.productionSafe,false);assert.match(storage.recommendation,/Render Postgres/);
});
