// Read-only hosted acceptance. Never queue/send/mark-sent or change operational records.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.APP_URL||'https://splicing-planning-assistant.onrender.com';const results=[];await mkdir('test-results',{recursive:true});let browser;
try{
 const r=await fetch(base+'/api/build',{signal:AbortSignal.timeout(90000)});assert.equal(r.status,200,'Hosted /api/build missing; deploy required');const build=await r.json();assert.equal(build.version,'R20-workflow');if(process.env.EXPECTED_COMMIT)assert.equal(build.commit,process.env.EXPECTED_COMMIT);
 results.push({name:'hosted build',pass:true,build});
 browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const context=await browser.newContext({baseURL:base,viewport:{width:1700,height:1100}}),page=await context.newPage(),errors=[];page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{const req=route.request();if(req.method()==='GET')return route.continue();let b={};try{b=req.postDataJSON()||{};}catch{}if(req.url().endsWith('/api/capture/field-preview')||req.url().endsWith('/api/monday/dual-comment')&&b.dryRun===true)return route.continue();return route.abort('blockedbyclient');});
 await page.goto(base,{waitUntil:'networkidle'});await page.locator('#health').filter({hasText:build.commit.slice(0,12)}).waitFor();results.push({name:'visible hosted build matches API',pass:true});
 for(const key of ['All open','Ready','Conditional','Blocked','Unassigned resource','Needs update','Readiness blockers','Source bridge gaps','Schedule candidates']){await page.locator('#chips').getByRole('button',{name:key,exact:true}).click();assert((await page.locator('#workflowStatus').innerText()).startsWith(key+':'));}results.push({name:'hosted generalized filters',pass:true});
 await page.locator('#chips').getByRole('button',{name:'All open',exact:true}).click();await page.locator('#list .card').first().click();await page.locator('#inspector[data-loading="false"] #pcNotes').waitFor();const id=await page.evaluate(()=>selected.itemId);const detail=await (await context.request.get('/api/item/'+id)).json();assert(detail.item.sourceBoardId);assert(detail.bridge.status);results.push({name:'real record selection/source/bridge',pass:true,itemId:id,bridgeStatus:detail.bridge.status,observationSource:detail.item.observationSource});
 await page.locator('#pcNotes').fill('RFS date to 2026-11-25; priority high; blocker is awaiting permit; action is confirm permit checkpoint.');await page.getByRole('button',{name:'Extract into fields',exact:true}).click();await page.waitForFunction(()=>document.getElementById('pcPreview').textContent.includes('Extracted'));assert.equal(await page.locator('#pcRfs').inputValue(),'2026-11-25');await page.locator('#pcBlocker').fill('Draft test only; do not send');await page.getByRole('button',{name:'Add update to draft',exact:true}).click();assert((await page.locator('#draft').inputValue()).includes('Draft test only'));results.push({name:'hosted extraction and local editable draft',pass:true});
 await page.locator('#dest').selectOption('primary');await page.getByRole('button',{name:'Dry run',exact:true}).click();await page.locator('#writeState').filter({hasText:'Dry run passed'}).waitFor();results.push({name:'hosted primary dry run only',pass:true});
 const people=await(await context.request.get('/api/people?refresh=1')).json();results.push({name:'Monday users live lookup',pass:people.source==='Monday API'&&people.users.length>0,source:people.source,count:people.users.length});
 await page.screenshot({path:'test-results/hosted-editor.png',fullPage:true});
 await page.getByRole('button',{name:'Tuesday RFS Prep',exact:true}).click();await page.locator('#tuesdayRows').filter({hasText:'automatic sending disabled'}).waitFor();results.push({name:'hosted Tuesday preview no send',pass:true});await page.screenshot({path:'test-results/hosted-tuesday.png',fullPage:true});
 assert.deepEqual(errors,[]);results.push({name:'no hosted JavaScript errors',pass:true});
}catch(e){results.push({name:'hosted acceptance',pass:false,error:e.message});process.exitCode=1;}finally{await browser?.close();await writeFile('test-results/hosted-results.json',JSON.stringify({scope:'read-only hosted checks; queue, live post/readback, native mentions and all-feature acceptance remain unverified',results},null,2));console.log(JSON.stringify(results,null,2));if(results.some(x=>!x.pass))process.exitCode=1;}
