import test from 'node:test';import assert from 'node:assert/strict';import {activeRecords,normalizeItem,readBoards} from '../lib/live-sync.mjs';import {bridgeFor} from '../lib/workflow.mjs';import {tuesdayWorkflow} from '../lib/tuesday.mjs';
test('complete live batch replaces snapshots, no stale seed union',()=>{const r=activeRecords({records:[{itemId:'old'}]},{complete:true,syncedAt:'now',records:[{itemId:'new'}]});assert.deepEqual(r.map(x=>x.itemId),['new']);assert.equal(r[0].observationSource,'Monday sync');});
test('pagination exhausts both requested boards before publication',async()=>{let calls=0;const r=await readBoards(async(q,v)=>{calls++;return q.includes('next_items_page')?{next_items_page:{cursor:null,items:[{id:'2',name:'second'}]}}:{boards:[{id:v.ids[0],name:'Board',items_page:{cursor:v.ids[0]==='18391791372'?'cursor':null,items:[{id:v.ids[0],name:'first'}]}}]};});assert.equal(calls,3);assert.equal(r.records.length,3);assert(r.complete);assert(r.boards.every(b=>b.complete));});
test('missing board throws instead of false successful partial sync',async()=>{await assert.rejects(()=>readBoards(async()=>({boards:[]})),/unavailable/);});
test('actual D2D mirror and install columns normalized without invented dates',()=>{const r=normalizeItem({id:'18391791372',name:'D2D'},{id:'1',name:'X',column_values:[{id:'a',column:{title:'Fiber Team RFS'},display_value:'2026-11-25'},{id:'b',column:{title:'New Zone Install Date'},text:'2026-11-30'},{id:'c',column:{title:'Construction Manager'},display_value:'Owner'},{id:'d',column:{title:'Fiber Zone Status'},display_value:'Complete/Live'}]},'now');assert.equal(r.rfs,'2026-11-25');assert.equal(r.installDate,'2026-11-30');assert.equal(r.owner,'Owner');assert.equal(r.fiberStatus,'Complete/Live');assert.equal(r.score,'');});
test('exact live board relation verifies; similar names and ambiguous relation do not',()=>{const a={itemId:'1',sourceBoardId:'18391791372',observationSource:'Monday sync',sourceRelations:[{columnId:'c',columnTitle:'Project Tracker',linkedItemIds:['2']}]},b={itemId:'2',sourceBoardId:'5077578194',observationSource:'Monday sync',name:'same'};assert(bridgeFor(a,[a,b]).verified);assert(!bridgeFor({...a,sourceRelations:[]},[{...a,sourceRelations:[]},b]).verified);const c={...b,itemId:'3'};assert(!bridgeFor({...a,sourceRelations:[{columnId:'c',linkedItemIds:['2','3']}]},[{...a,sourceRelations:[{columnId:'c',linkedItemIds:['2','3']}]},b,c]).verified);});
test('Tuesday excludes every packaged snapshot',async()=>{const tw=tuesdayWorkflow({allItems:async()=>[{itemId:'1',sourceBoardId:'18391791372',name:'Snapshot',observationSource:'packaged snapshot'}],files:{bridge:'b',tuesday:'t'},readJson:async(p,f)=>f});const p=await tw.preview();assert.equal(p.groups.length,0);assert.equal(p.excludedSnapshotRecords,1);assert.equal(p.liveOnly,true);});
test('explicit intermediate relation plus unique project ID verifies, conflicting project IDs fail closed',()=>{
 const d={itemId:'10',sourceBoardId:'18391791372',observationSource:'Monday sync',identityEvidence:[{itemId:'30',boardId:'40',projectId:'F123',name:'Town Alpha MDU',observedAt:'now',relationColumnId:'r',columnId:'p'}]},t={itemId:'20',sourceBoardId:'5077578194',projectId:'F123',name:'Town Alpha Apartments - 40 Passings',observationSource:'Monday sync'};
 assert(bridgeFor(d,[d,t]).verified);assert.match(bridgeFor(d,[d,t]).reason,/F123/);
 assert(!bridgeFor(d,[d,t,{...t,itemId:'21'}]).verified);
 assert(!bridgeFor(d,[d,t,{...d,itemId:'11'}]).verified);
 assert(!bridgeFor(d,[d,{...t,projectId:'F124'}]).verified);
});

test('shared project identifier does not authorize a different sub-scope',()=>{const d={itemId:'1',sourceBoardId:'18391791372',observationSource:'Monday sync',identityEvidence:[{projectId:'F1',name:'Lake Phase 2',observedAt:'now'}]},t={itemId:'2',sourceBoardId:'5077578194',observationSource:'Monday sync',projectId:'F1',name:'POP fence'};assert(!bridgeFor(d,[d,t]).verified);assert.match(bridgeFor(d,[d,t]).reason,/scope/);});
