import {readFile,writeFile,rename} from 'node:fs/promises';
import crypto from 'node:crypto';
export async function createStorage({databaseUrl,files}){
 if(databaseUrl){
  const {Pool}=await import('pg');const pool=new Pool({connectionString:databaseUrl,ssl:databaseUrl.includes('render.com')?{rejectUnauthorized:false}:undefined});
  await pool.query(`CREATE TABLE IF NOT EXISTS spa_requests(id TEXT PRIMARY KEY, idempotency_key TEXT UNIQUE NOT NULL, item_id TEXT NOT NULL, recipient TEXT, message TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, attempted_at TIMESTAMPTZ, result JSONB); CREATE TABLE IF NOT EXISTS spa_targets(id BIGSERIAL PRIMARY KEY, request_id TEXT NOT NULL REFERENCES spa_requests(id), board_id TEXT NOT NULL, item_id TEXT NOT NULL, message TEXT NOT NULL, recipient TEXT, tag_text TEXT, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, attempted_at TIMESTAMPTZ, result JSONB, update_id TEXT, error TEXT, UNIQUE(request_id,board_id,item_id)); CREATE TABLE IF NOT EXISTS spa_audit(id BIGSERIAL PRIMARY KEY, request_id TEXT, event TEXT NOT NULL, target_ids JSONB, recipient TEXT, message TEXT, status TEXT, idempotency_key TEXT, created_at TIMESTAMPTZ NOT NULL, detail JSONB); CREATE TABLE IF NOT EXISTS spa_contacts(display_name TEXT PRIMARY KEY, preferred_first_name TEXT, role_team TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, monday_user_id TEXT, monday_account_email TEXT, email_address TEXT, teams_identity TEXT, default_tuesday_recipient BOOLEAN NOT NULL DEFAULT FALSE, allowed_delivery_methods JSONB NOT NULL DEFAULT '[\"copy/export only\"]', notes TEXT, last_verified_at TIMESTAMPTZ, source TEXT);`);
  return {kind:'postgres',productionSafe:true,async close(){await pool.end()},async contacts(){return (await pool.query('SELECT * FROM spa_contacts ORDER BY display_name')).rows},async upsertContact(c){const q=await pool.query("INSERT INTO spa_contacts(display_name,preferred_first_name,role_team,active,monday_user_id,monday_account_email,email_address,teams_identity,default_tuesday_recipient,allowed_delivery_methods,notes,last_verified_at,source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(display_name) DO UPDATE SET preferred_first_name=EXCLUDED.preferred_first_name,active=EXCLUDED.active,monday_user_id=EXCLUDED.monday_user_id,monday_account_email=EXCLUDED.monday_account_email,last_verified_at=EXCLUDED.last_verified_at,source=EXCLUDED.source RETURNING *",[c.displayName,c.preferredFirstName,c.roleTeam,c.active,c.mondayUserId,c.mondayAccountEmail,c.emailAddress,c.teamsIdentity,c.defaultTuesdayRecipient,JSON.stringify(c.allowedDeliveryMethods||['copy/export only']),c.notes,c.lastVerifiedAt,c.source]);return q.rows[0]},async enqueue(e){const q=await pool.query(`INSERT INTO spa_requests(id,idempotency_key,item_id,recipient,message,status,created_at,result) VALUES($1,$2,$3,$4,$5,'queued',$6,$7) ON CONFLICT(idempotency_key) DO UPDATE SET id=spa_requests.id RETURNING *`,[e.id,e.key,e.itemId,e.recipient||'',e.message,e.createdAt,e]);const req=q.rows[0];for(const t of e.planned||[])await pool.query(`INSERT INTO spa_targets(request_id,board_id,item_id,message,recipient,tag_text,status,created_at) VALUES($1,$2,$3,$4,$5,$6,'queued',$7) ON CONFLICT DO NOTHING`,[req.id,t.boardId,t.itemId,e.message,e.recipient||'',e.tagText||'',e.createdAt]);return req},async queue(){const q=await pool.query('SELECT * FROM spa_requests ORDER BY created_at DESC');return q.rows},async audit(e){await pool.query(`INSERT INTO spa_audit(request_id,event,target_ids,recipient,message,status,idempotency_key,created_at,detail) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[e.requestId||null,e.event,JSON.stringify(e.targets||[]),e.recipient||'',e.message||'',e.status||'',e.idempotencyKey||'',e.timestamp||new Date(),JSON.stringify(e)]);},async auditRows(){return (await pool.query('SELECT * FROM spa_audit ORDER BY created_at DESC')).rows},async request(id){return (await pool.query('SELECT * FROM spa_requests WHERE id=$1 OR idempotency_key=$1',[id])).rows[0]},async targets(id){return (await pool.query('SELECT * FROM spa_targets WHERE request_id=$1 ORDER BY id',[id])).rows},async targetUpdate(id,t){await pool.query(`UPDATE spa_targets SET status=$2,attempted_at=COALESCE(attempted_at,$3),result=$4,update_id=$5,error=$6 WHERE request_id=$1 AND board_id=$7 AND item_id=$8`,[id,t.status,new Date(),JSON.stringify(t.result||{}),t.updateId||null,t.error||null,t.boardId,t.itemId]);},async requestUpdate(id,status,result){await pool.query('UPDATE spa_requests SET status=$2,attempted_at=COALESCE(attempted_at,$3),result=$4 WHERE id=$1',[id,status,new Date(),JSON.stringify(result||{})]);}};
 }
 async function json(file,f){try{return JSON.parse(await readFile(file,'utf8'))}catch{return f}}
 async function save(file,v){const t=file+'.tmp';await writeFile(t,JSON.stringify(v,null,2));await rename(t,file)}
 return {kind:'json',productionSafe:false,warning:'Development-only local JSON; not durable across Render restart/redeploy.',async enqueue(e){let q=await json(files.queue,[]);let x=q.find(a=>a.key===e.key);if(!x){x={...e,status:'queued'};q.unshift(x);await save(files.queue,q)}return x},async queue(){return json(files.queue,[])},async audit(e){let a=await json(files.audit,[]);a.unshift(e);await save(files.audit,a)},async auditRows(){return json(files.audit,[])},async request(id){return (await json(files.queue,[])).find(x=>x.id===id||x.key===id)},async targets(){return []},async targetUpdate(){},async requestUpdate(){},async close(){}};
}
